In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/Manju410/MLPractice/main/data/Cardetails.csv')
df.head()

name  year  ...                    torque  seats
0        Maruti Swift Dzire VDI  2014  ...            190Nm@ 2000rpm    5.0
1  Skoda Rapid 1.5 TDI Ambition  2014  ...       250Nm@ 1500-2500rpm    5.0
2      Honda City 2017-2020 EXi  2006  ...     12.7@ 2,700(kgm@ rpm)    5.0
3     Hyundai i20 Sportz Diesel  2010  ...  22.4 kgm at 1750-2750rpm    5.0
4        Maruti Swift VXI BSIII  2007  ...     11.5@ 4,500(kgm@ rpm)    5.0

[5 rows x 13 columns]

In [6]:
df.shape

(8128, 13)

In [7]:
df.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner', 'mileage', 'engine', 'max_power', 'torque',
       'seats'],
      dtype='object')

In [8]:
df.isna().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   name           8128 non-null   object 
 1   year           8128 non-null   int64  
 2   selling_price  8128 non-null   int64  
 3   km_driven      8128 non-null   int64  
 4   fuel           8128 non-null   object 
 5   seller_type    8128 non-null   object 
 6   transmission   8128 non-null   object 
 7   owner          8128 non-null   object 
 8   mileage        7907 non-null   object 
 9   engine         7907 non-null   object 
 10  max_power      7913 non-null   object 
 11  torque         7906 non-null   object 
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB


In [10]:
df.name.unique()

array(['Maruti Swift Dzire VDI', 'Skoda Rapid 1.5 TDI Ambition',
       'Honda City 2017-2020 EXi', ..., 'Tata Nexon 1.5 Revotorq XT',
       'Ford Freestyle Titanium Plus Diesel BSIV',
       'Toyota Innova 2.5 GX (Diesel) 8 Seater BS IV'], dtype=object)

In [11]:
x='Maruti Swift Dzire VDI'

In [12]:
x.split(' ')[0]

'Maruti'

In [13]:
x.split(' ')[1]

'Swift'

In [15]:
#[x.split(' ')[0] for x in df['name']]
df['name'].apply(lambda x: x.split(' ')[1])[:5]

0    Swift
1    Rapid
2     City
3      i20
4    Swift
Name: name, dtype: object

In [23]:
df.name.str.split(' ').str[:2].str.join(' ')[:5]

0    Maruti Swift
1     Skoda Rapid
2      Honda City
3     Hyundai i20
4    Maruti Swift
Name: name, dtype: object

In [ ]:
import re

In [ ]:
def carname(name):
  if re.match("Maruti",name):return "Maruti"
  elif re.match("Honda",name): return "Honda"
  elif re.match("Toyota",name): return "Toyota"
  elif re.match("Mercedes",name): return "Mercedes"
  elif re.match("Tata",name): return "Tata"
  elif re.match("Jeep",name): return "Jeep"
  elif re.match("Hyundai",name): return "Hyundai"
  elif re.match("Fiat",name): return "Fiat"
  elif re.match("Chevrolet",name): return "Chevrolet"
  elif re.match("Mahindra",name): return "Mahindra"
  elif re.match("Skoda",name): return "Skoda"
  elif re.match("Renault",name): return "Renault"
  elif re.match("Ford",name): return "Ford"
  else: return "Other Cars"

In [ ]:
df['name'] = df.name.apply(carname)

In [ ]:
len(df.name.unique())

14

In [ ]:
df.name.value_counts()

Maruti        2448
Hyundai       1415
Mahindra       772
Tata           734
Other Cars     712
Toyota         488
Honda          467
Ford           397
Chevrolet      230
Renault        228
Skoda          105
Mercedes        54
Fiat            47
Jeep            31
Name: name, dtype: int64

In [ ]:
df.year.unique()

array([2014, 2006, 2010, 2007, 2017, 2001, 2011, 2013, 2005, 2009, 2016,
       2012, 2002, 2015, 2018, 2003, 2019, 2008, 2020, 1999, 2000, 1983,
       2004, 1996, 1994, 1995, 1998, 1997, 1991])

In [ ]:
df.fuel.unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [ ]:
df.seller_type.unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [ ]:
df.transmission.unique()

array(['Manual', 'Automatic'], dtype=object)

In [ ]:
df.owner.unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner', 'Test Drive Car'], dtype=object)

In [ ]:
from numpy.core.numeric import NaN
def integer(val):
  z = re.match("[0-9.]+",str(val));
  if z: return str(z.group())
  else: return NaN

In [ ]:
df.mileage = df.mileage.apply(integer)

In [ ]:
df['mileage'] = df['mileage'].astype(float)

In [ ]:
df.mileage.fillna(df.mileage.mean(),inplace=True)

In [ ]:
df.engine = df.engine.apply(integer)

In [ ]:
df.engine.fillna(df.engine.value_counts().index[0],inplace=True)

In [ ]:
df['engine'] = df['engine'].astype(int)

In [ ]:
df.engine.unique()

array([1248, 1498, 1497, 1396, 1298, 1197, 1061,  796, 1364, 1399, 1461,
        993, 1198, 1199,  998, 1591, 2179, 1368, 2982, 2494, 2143, 2477,
       1462, 2755, 1968, 1798, 1196, 1373, 1598, 1998, 1086, 1194, 1172,
       1405, 1582,  999, 2487, 1999, 3604, 2987, 1995, 1451, 1969, 2967,
       2497, 1797, 1991, 2362, 1493, 1599, 1341, 1794,  799, 1193, 2696,
       1495, 1186, 1047, 2498, 2956, 2523, 1120,  624, 1496, 1984, 2354,
        814,  793, 1799,  936, 1956, 1997, 1499, 1948, 2997, 2489, 2499,
       2609, 2953, 1150, 1994, 1388, 1527, 2199,  995, 2993, 1586, 1390,
        909, 2393, 3198, 1339, 2835, 2092, 1595, 2496, 1596, 1597, 2596,
       2148, 1299, 1590, 2231, 2694, 2200, 1795, 1896, 1796, 1422, 1489,
       2359, 2197, 2999, 1781, 2650, 1343, 2446, 3498, 2198, 2776, 1950])

In [ ]:
df.engine.value_counts().index[0]

1248

In [ ]:
df.max_power = df.max_power.apply(integer)

In [ ]:
df['max_power'] = df['max_power'].astype(float)

In [ ]:
df.max_power.fillna(df.max_power.mean(),inplace=True)

In [ ]:
df.max_power.unique()

array([ 74.        , 103.52      ,  78.        ,  90.        ,
        88.2       ,  81.86      ,  57.5       ,  37.        ,
        67.1       ,  68.1       , 108.45      ,  60.        ,
        73.9       ,  91.51791898,  67.        ,  82.        ,
        88.5       ,  46.3       ,  88.73      ,  64.1       ,
        98.6       ,  88.8       ,  83.81      ,  83.1       ,
        47.3       ,  73.8       ,  34.2       ,  35.        ,
        81.83      ,  40.3       , 121.3       , 138.03      ,
       160.77      , 117.3       , 116.3       ,  83.14      ,
        67.05      , 168.5       , 100.        , 120.7       ,
        98.63      , 175.56      , 103.25      , 171.5       ,
       100.6       , 174.33      , 187.74      , 170.        ,
        78.9       ,  88.76      ,  86.8       , 108.495     ,
       108.62      ,  93.7       , 103.6       ,  98.59      ,
       189.        ,  67.04      ,  68.05      ,  58.2       ,
        82.85      ,  81.8       ,  73.        , 120.  

In [ ]:
df.torque[:5]

0              190Nm@ 2000rpm
1         250Nm@ 1500-2500rpm
2       12.7@ 2,700(kgm@ rpm)
3    22.4 kgm at 1750-2750rpm
4       11.5@ 4,500(kgm@ rpm)
Name: torque, dtype: object

In [ ]:
integer("190Nm@ 2000rpm")

'190'

In [ ]:
df.torque = df.torque.apply(integer)

In [ ]:
df['torque'] = df['torque'].astype(float)

In [ ]:
df.torque.fillna(df.torque.mean(),inplace=True)

In [ ]:
df.torque.unique()

array([190.        , 250.        ,  12.7       ,  22.4       ,
        11.5       , 113.75      ,   7.8       ,  59.        ,
       170.        , 160.        , 248.        ,  78.        ,
       168.29414116,  84.        , 115.        , 200.        ,
        62.        , 219.7       , 114.        ,  69.        ,
       172.5       ,   6.1       , 114.7       ,  60.        ,
        90.        , 151.        , 104.        , 320.        ,
       145.        , 146.        , 343.        , 400.        ,
       138.        , 360.        , 380.        , 173.        ,
       111.7       , 219.6       , 112.        , 130.        ,
       205.        , 280.        ,  99.04      ,  77.        ,
       110.        , 153.        , 113.7       , 113.        ,
       101.        , 290.        , 120.        ,  96.        ,
       135.        , 259.8       , 259.9       ,  91.        ,
        96.1       , 109.        , 202.        , 430.        ,
       347.        , 382.        , 620.        , 500.  

In [ ]:
df.seats.unique()

array([ 5.,  4., nan,  7.,  8.,  6.,  9., 10., 14.,  2.])

In [ ]:
df.seats.fillna(df.seats.value_counts().index[0],inplace=True)

In [ ]:
df.isna().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
mileage          0
engine           0
max_power        0
torque           0
seats            0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   name           8128 non-null   object 
 1   year           8128 non-null   int64  
 2   selling_price  8128 non-null   int64  
 3   km_driven      8128 non-null   int64  
 4   fuel           8128 non-null   object 
 5   seller_type    8128 non-null   object 
 6   transmission   8128 non-null   object 
 7   owner          8128 non-null   object 
 8   mileage        8128 non-null   float64
 9   engine         8128 non-null   int64  
 10  max_power      8128 non-null   float64
 11  torque         8128 non-null   float64
 12  seats          8128 non-null   float64
dtypes: float64(4), int64(4), object(5)
memory usage: 825.6+ KB


In [ ]:
df.head()

name  year  selling_price  km_driven  ... engine max_power torque seats
0   Maruti  2014         450000     145500  ...   1248     74.00  190.0   5.0
1    Skoda  2014         370000     120000  ...   1498    103.52  250.0   5.0
2    Honda  2006         158000     140000  ...   1497     78.00   12.7   5.0
3  Hyundai  2010         225000     127000  ...   1396     90.00   22.4   5.0
4   Maruti  2007         130000     120000  ...   1298     88.20   11.5   5.0

[5 rows x 13 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
label_encod = LabelEncoder()

In [ ]:
df.name = label_encod.fit_transform(df.name)

In [ ]:
df.name.unique()

array([ 7, 11,  3,  4, 13,  2, 10,  6, 12,  0,  1,  9,  5,  8])

In [ ]:
cat_col = df.dtypes[df.dtypes =='object'].index.tolist()
cat_col

['fuel', 'seller_type', 'transmission', 'owner']

In [ ]:
def catconvert(df,catcol):
  continueval = []
  continueval.append(df)
  for col in catcol:
    tempdf = pd.get_dummies(df[col],prefix=col)
    continueval.append(tempdf)

  dffinal = pd.concat(continueval,axis=1)
  dffinal.drop(columns=catcol, axis=1, inplace=True)  
  return dffinal

In [ ]:
finaldf = catconvert(df,cat_col)
finaldf.head()

name  year  ...  owner_Test Drive Car  owner_Third Owner
0     7  2014  ...                     0                  0
1    11  2014  ...                     0                  0
2     3  2006  ...                     0                  1
3     4  2010  ...                     0                  0
4     7  2007  ...                     0                  0

[5 rows x 23 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
finaldf.to_csv('/content/drive/MyDrive/CarDetails_Cleanup.csv', index=False)