In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/Manju410/MLPractice/main/data/Employee_Cleanup.csv')
df.head()

DEPARTMENT_ID  SALARY  ...  JOB_ID_ST_CLERK  JOB_ID_ST_MAN
0           60.0  9000.0  ...                0              0
1           60.0  6000.0  ...                0              0
2           60.0  4800.0  ...                0              0
3           60.0  4800.0  ...                0              0
4           60.0  4200.0  ...                0              0

[5 rows x 115 columns]

In [3]:
df.shape

(10600, 115)

In [4]:
df.columns

Index(['DEPARTMENT_ID', 'SALARY', 'DEPARTMENT_ID_1', 'LOCATION_ID',
       'LOCATION_ID_1', 'REGION_ID', 'REGION_ID_1',
       'DEPARTMENT_NAME_Accounting', 'DEPARTMENT_NAME_Administration',
       'DEPARTMENT_NAME_Executive',
       ...
       'JOB_ID_MK_MAN', 'JOB_ID_MK_REP', 'JOB_ID_PR_REP', 'JOB_ID_PU_CLERK',
       'JOB_ID_PU_MAN', 'JOB_ID_SA_MAN', 'JOB_ID_SA_REP', 'JOB_ID_SH_CLERK',
       'JOB_ID_ST_CLERK', 'JOB_ID_ST_MAN'],
      dtype='object', length=115)

In [5]:
X = df.drop(['SALARY'],axis=1)
y= df.SALARY

In [6]:
X.shape,y.shape

((10600, 114), (10600,))

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=1234)

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
mmscaler = MinMaxScaler()

In [11]:
X_train.head()

DEPARTMENT_ID  DEPARTMENT_ID_1  ...  JOB_ID_ST_CLERK  JOB_ID_ST_MAN
9747           80.0             80.0  ...                0              0
2255           80.0             80.0  ...                0              0
9987           80.0             80.0  ...                0              0
1659          100.0            100.0  ...                0              0
6511           50.0             50.0  ...                1              0

[5 rows x 114 columns]

In [12]:
continuoscol = ['DEPARTMENT_ID','DEPARTMENT_ID_1','LOCATION_ID','LOCATION_ID_1','REGION_ID','REGION_ID_1']

In [13]:
scaler = mmscaler.fit(X_train[continuoscol])

In [14]:
scaler.data_max_

array([ 110.,  110., 2700., 2700.,    4.,    4.])

In [15]:
scaler.data_min_

array([1.0e+01, 1.0e+01, 1.4e+03, 1.4e+03, 1.0e+00, 1.0e+00])

In [16]:
scaled_vals = scaler.transform(X_train[continuoscol])

In [17]:
scaled_vals1 = scaler.transform(X_test[continuoscol])

In [18]:
X_test_scaled = pd.DataFrame(scaled_vals1,columns=continuoscol,index=X_test.index)
X_test_scaled.head()

DEPARTMENT_ID  DEPARTMENT_ID_1  ...  REGION_ID  REGION_ID_1
3317            0.4              0.4  ...        1.0     0.333333
5109            0.7              0.7  ...        0.0     0.333333
3274            0.4              0.4  ...        0.0     0.333333
9108            0.4              0.4  ...        1.0     1.000000
545             0.4              0.4  ...        0.0     0.000000

[5 rows x 6 columns]

In [19]:
X_train_scaled = pd.DataFrame(scaled_vals,columns=continuoscol,index=X_train.index)
X_train_scaled.head()

DEPARTMENT_ID  DEPARTMENT_ID_1  ...  REGION_ID  REGION_ID_1
9747            0.7              0.7  ...   0.000000     1.000000
2255            0.7              0.7  ...   0.333333     0.000000
9987            0.7              0.7  ...   1.000000     1.000000
1659            0.9              0.9  ...   1.000000     0.000000
6511            0.4              0.4  ...   0.000000     0.666667

[5 rows x 6 columns]

In [20]:
X_train.drop(columns=continuoscol,axis=1,inplace=True)

In [21]:

X_train.insert(0,X_train_scaled.columns[0],X_train_scaled[X_train_scaled.columns[0]])
X_train.insert(1,X_train_scaled.columns[1],X_train_scaled[X_train_scaled.columns[1]])
X_train.insert(2,X_train_scaled.columns[2],X_train_scaled[X_train_scaled.columns[2]])
X_train.insert(3,X_train_scaled.columns[3],X_train_scaled[X_train_scaled.columns[3]])
X_train.insert(4,X_train_scaled.columns[4],X_train_scaled[X_train_scaled.columns[4]])
X_train.insert(5,X_train_scaled.columns[5],X_train_scaled[X_train_scaled.columns[5]])

In [22]:

X_train.head()

DEPARTMENT_ID  DEPARTMENT_ID_1  ...  JOB_ID_ST_CLERK  JOB_ID_ST_MAN
9747            0.7              0.7  ...                0              0
2255            0.7              0.7  ...                0              0
9987            0.7              0.7  ...                0              0
1659            0.9              0.9  ...                0              0
6511            0.4              0.4  ...                1              0

[5 rows x 114 columns]

In [23]:
X_test.drop(columns=continuoscol,axis=1,inplace=True)
X_test.insert(0,X_test_scaled.columns[0],X_test_scaled[X_test_scaled.columns[0]])
X_test.insert(1,X_test_scaled.columns[1],X_test_scaled[X_test_scaled.columns[1]])
X_test.insert(2,X_test_scaled.columns[2],X_test_scaled[X_test_scaled.columns[2]])
X_test.insert(3,X_test_scaled.columns[3],X_test_scaled[X_test_scaled.columns[3]])
X_test.insert(4,X_test_scaled.columns[4],X_test_scaled[X_test_scaled.columns[4]])
X_test.insert(5,X_test_scaled.columns[5],X_test_scaled[X_test_scaled.columns[5]])

In [24]:
X_test.head()

DEPARTMENT_ID  DEPARTMENT_ID_1  ...  JOB_ID_ST_CLERK  JOB_ID_ST_MAN
3317            0.4              0.4  ...                0              1
5109            0.7              0.7  ...                0              0
3274            0.4              0.4  ...                0              1
9108            0.4              0.4  ...                0              0
545             0.4              0.4  ...                1              0

[5 rows x 114 columns]

In [27]:
from sklearn.feature_selection import SequentialFeatureSelector

In [28]:
from sklearn.linear_model import LinearRegression

In [30]:
linmodel = LinearRegression()

In [31]:
sfs = SequentialFeatureSelector(linmodel, n_features_to_select=13,cv=10,direction='forward',scoring='neg_mean_squared_error')

sfs1 = sfs.fit(X_train, y_train)

In [39]:
sfs1.support_


array([False, False, False, False, False, False, False, False,  True,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
       False, False,  True, False, False,  True,  True, False,  True,
        True,  True, False, False, False,  True])

In [40]:
best_features = [name for name,sup in zip(X_train.columns,sfs1.support_) if sup== True]
best_features

['DEPARTMENT_NAME_Executive',
 'DEPARTMENT_NAME_IT',
 'DEPARTMENT_NAME_Shipping',
 'JOB_ID_AC_MGR',
 'JOB_ID_AD_ASST',
 'JOB_ID_AD_PRES',
 'JOB_ID_FI_MGR',
 'JOB_ID_MK_MAN',
 'JOB_ID_MK_REP',
 'JOB_ID_PU_CLERK',
 'JOB_ID_PU_MAN',
 'JOB_ID_SA_MAN',
 'JOB_ID_ST_MAN']

In [41]:
new_dfXtrain = X_train[best_features]
new_dfXtrain.head()

DEPARTMENT_NAME_Executive  ...  JOB_ID_ST_MAN
9747                          0  ...              0
2255                          0  ...              0
9987                          0  ...              0
1659                          0  ...              0
6511                          0  ...              0

[5 rows x 13 columns]

In [42]:
new_dfXtest = X_test[best_features]
new_dfXtest

DEPARTMENT_NAME_Executive  ...  JOB_ID_ST_MAN
3317                          0  ...              1
5109                          0  ...              0
3274                          0  ...              1
9108                          0  ...              0
545                           0  ...              0
...                         ...  ...            ...
8025                          0  ...              0
3185                          0  ...              0
7468                          0  ...              0
4924                          0  ...              0
4048                          0  ...              0

[2650 rows x 13 columns]

In [43]:
new_dfXtrain.shape,new_dfXtest.shape

((7950, 13), (2650, 13))

In [44]:
linmodel.fit(new_dfXtrain,y_train)

LinearRegression()

In [45]:
y_pred = linmodel.predict(new_dfXtest)

In [46]:
df_coeff = pd.DataFrame({'columns':new_dfXtrain.columns,'coeff':linmodel.coef_})
df_coeff

columns        coeff
0   DEPARTMENT_NAME_Executive  8663.068592
1          DEPARTMENT_NAME_IT -2597.521220
2    DEPARTMENT_NAME_Shipping -5332.638987
3               JOB_ID_AC_MGR  3663.068592
4              JOB_ID_AD_ASST -3936.931408
5              JOB_ID_AD_PRES  7000.000000
6               JOB_ID_FI_MGR  3663.068592
7               JOB_ID_MK_MAN  4663.068592
8               JOB_ID_MK_REP -2336.931408
9             JOB_ID_PU_CLERK -5563.874413
10              JOB_ID_PU_MAN  2663.068592
11              JOB_ID_SA_MAN  3855.680729
12              JOB_ID_ST_MAN  4262.728855

In [47]:
residuals = pd.DataFrame({'pred':y_pred,'actul':y_test})
residuals.head()

pred    actul
3317   7267.021277   7900.0
5109  12192.612137  10500.0
3274   7267.021277   5800.0
9108   3004.292421   2600.0
545    3004.292421   2400.0

In [48]:
from sklearn.metrics import r2_score

In [49]:
r2_score(y_pred,y_test)

0.9198714220332139