In [115]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [116]:
df = pd.read_csv('https://raw.githubusercontent.com/Manju410/MLPractice/main/data/Employee_Cleanup.csv')
df.head()

DEPARTMENT_ID  SALARY  ...  JOB_ID_ST_CLERK  JOB_ID_ST_MAN
0           60.0  9000.0  ...                0              0
1           60.0  6000.0  ...                0              0
2           60.0  4800.0  ...                0              0
3           60.0  4800.0  ...                0              0
4           60.0  4200.0  ...                0              0

[5 rows x 115 columns]

In [117]:
df.shape

(10600, 115)

In [118]:
df.columns

Index(['DEPARTMENT_ID', 'SALARY', 'DEPARTMENT_ID_1', 'LOCATION_ID',
       'LOCATION_ID_1', 'REGION_ID', 'REGION_ID_1',
       'DEPARTMENT_NAME_Accounting', 'DEPARTMENT_NAME_Administration',
       'DEPARTMENT_NAME_Executive',
       ...
       'JOB_ID_MK_MAN', 'JOB_ID_MK_REP', 'JOB_ID_PR_REP', 'JOB_ID_PU_CLERK',
       'JOB_ID_PU_MAN', 'JOB_ID_SA_MAN', 'JOB_ID_SA_REP', 'JOB_ID_SH_CLERK',
       'JOB_ID_ST_CLERK', 'JOB_ID_ST_MAN'],
      dtype='object', length=115)

In [119]:
X = df.drop(['SALARY'],axis=1)
y= df.SALARY

In [120]:
X.shape,y.shape

((10600, 114), (10600,))

In [121]:
from sklearn.model_selection import train_test_split

In [122]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=1234)

In [123]:
from sklearn.preprocessing import MinMaxScaler

In [124]:
mmscaler = MinMaxScaler()

In [125]:
X_train.head()

DEPARTMENT_ID  DEPARTMENT_ID_1  ...  JOB_ID_ST_CLERK  JOB_ID_ST_MAN
9747           80.0             80.0  ...                0              0
2255           80.0             80.0  ...                0              0
9987           80.0             80.0  ...                0              0
1659          100.0            100.0  ...                0              0
6511           50.0             50.0  ...                1              0

[5 rows x 114 columns]

In [126]:
continuoscol = ['DEPARTMENT_ID','DEPARTMENT_ID_1','LOCATION_ID','LOCATION_ID_1','REGION_ID','REGION_ID_1']

In [127]:
scaler = mmscaler.fit(X_train[continuoscol])

In [128]:
scaler.data_max_

array([ 110.,  110., 2700., 2700.,    4.,    4.])

In [129]:
scaler.data_min_

array([1.0e+01, 1.0e+01, 1.4e+03, 1.4e+03, 1.0e+00, 1.0e+00])

In [130]:
scaled_vals = scaler.transform(X_train[continuoscol])

In [131]:
scaled_vals1 = scaler.transform(X_test[continuoscol])

In [132]:
X_test_scaled = pd.DataFrame(scaled_vals1,columns=continuoscol,index=X_test.index)
X_test_scaled.head()

DEPARTMENT_ID  DEPARTMENT_ID_1  ...  REGION_ID  REGION_ID_1
3317            0.4              0.4  ...        1.0     0.333333
5109            0.7              0.7  ...        0.0     0.333333
3274            0.4              0.4  ...        0.0     0.333333
9108            0.4              0.4  ...        1.0     1.000000
545             0.4              0.4  ...        0.0     0.000000

[5 rows x 6 columns]

In [133]:
X_train_scaled = pd.DataFrame(scaled_vals,columns=continuoscol,index=X_train.index)
X_train_scaled.head()

DEPARTMENT_ID  DEPARTMENT_ID_1  ...  REGION_ID  REGION_ID_1
9747            0.7              0.7  ...   0.000000     1.000000
2255            0.7              0.7  ...   0.333333     0.000000
9987            0.7              0.7  ...   1.000000     1.000000
1659            0.9              0.9  ...   1.000000     0.000000
6511            0.4              0.4  ...   0.000000     0.666667

[5 rows x 6 columns]

In [134]:
X_train.drop(columns=continuoscol,axis=1,inplace=True)

In [135]:

X_train.insert(0,X_train_scaled.columns[0],X_train_scaled[X_train_scaled.columns[0]])
X_train.insert(1,X_train_scaled.columns[1],X_train_scaled[X_train_scaled.columns[1]])
X_train.insert(2,X_train_scaled.columns[2],X_train_scaled[X_train_scaled.columns[2]])
X_train.insert(3,X_train_scaled.columns[3],X_train_scaled[X_train_scaled.columns[3]])
X_train.insert(4,X_train_scaled.columns[4],X_train_scaled[X_train_scaled.columns[4]])
X_train.insert(5,X_train_scaled.columns[5],X_train_scaled[X_train_scaled.columns[5]])

In [136]:

X_train.head()

DEPARTMENT_ID  DEPARTMENT_ID_1  ...  JOB_ID_ST_CLERK  JOB_ID_ST_MAN
9747            0.7              0.7  ...                0              0
2255            0.7              0.7  ...                0              0
9987            0.7              0.7  ...                0              0
1659            0.9              0.9  ...                0              0
6511            0.4              0.4  ...                1              0

[5 rows x 114 columns]

In [137]:
X_test.drop(columns=continuoscol,axis=1,inplace=True)
X_test.insert(0,X_test_scaled.columns[0],X_test_scaled[X_test_scaled.columns[0]])
X_test.insert(1,X_test_scaled.columns[1],X_test_scaled[X_test_scaled.columns[1]])
X_test.insert(2,X_test_scaled.columns[2],X_test_scaled[X_test_scaled.columns[2]])
X_test.insert(3,X_test_scaled.columns[3],X_test_scaled[X_test_scaled.columns[3]])
X_test.insert(4,X_test_scaled.columns[4],X_test_scaled[X_test_scaled.columns[4]])
X_test.insert(5,X_test_scaled.columns[5],X_test_scaled[X_test_scaled.columns[5]])

In [138]:
X_test.head()

DEPARTMENT_ID  DEPARTMENT_ID_1  ...  JOB_ID_ST_CLERK  JOB_ID_ST_MAN
3317            0.4              0.4  ...                0              1
5109            0.7              0.7  ...                0              0
3274            0.4              0.4  ...                0              1
9108            0.4              0.4  ...                0              0
545             0.4              0.4  ...                1              0

[5 rows x 114 columns]

In [139]:
from sklearn.linear_model import LinearRegression

In [140]:
linmodel = LinearRegression()

In [141]:
from sklearn.feature_selection import RFE
rfe_new = RFE(linmodel,n_features_to_select=30)
rfe_new.fit(X_train,y_train)

RFE(estimator=LinearRegression(), n_features_to_select=30)

In [142]:
rfe_new.support_

array([False, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False, False,  True,  True,
       False,  True, False,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True, False, False, False, False,
       False, False, False, False, False,  True,  True,  True, False,
       False,  True,  True, False, False, False])

In [143]:
best_col = [name for name,sup in zip(X_train.columns,rfe_new.support_) if sup== True]
best_col

['REGION_ID_1',
 'DEPARTMENT_NAME_Human Resources',
 'DEPARTMENT_NAME_Shipping',
 'CITY_London',
 'CITY_Oxford',
 'CITY_South San Francisco',
 'CITY_Toronto',
 'COUNTRY_ID_CA',
 'COUNTRY_ID_DE',
 'COUNTRY_ID_UK',
 'COUNTRY_ID_US',
 'STATE_PROVINCE_Bavaria',
 'STATE_PROVINCE_California',
 'STATE_PROVINCE_Ontario',
 'STATE_PROVINCE_Oxford',
 'STATE_PROVINCE_Texas',
 'STATE_PROVINCE_Washington',
 'STREET_ADDRESS_147 Spadina Ave',
 'STREET_ADDRESS_2011 Interiors Blvd',
 'STREET_ADDRESS_8204 Arthur St',
 'STREET_ADDRESS_Magdalen Centre, The Oxford Science Park',
 'STREET_ADDRESS_Schwanthalerstr. 7031',
 'REGION_NAME_Asia',
 'REGION_NAME_Europe',
 'REGION_NAME_Middle East and Africa',
 'JOB_ID_MK_MAN',
 'JOB_ID_MK_REP',
 'JOB_ID_PR_REP',
 'JOB_ID_SA_MAN',
 'JOB_ID_SA_REP']

In [144]:
new_dfXtrain = X_train[best_col]
new_dfXtrain.head()

REGION_ID_1  ...  JOB_ID_SA_REP
9747     1.000000  ...              1
2255     0.000000  ...              0
9987     1.000000  ...              1
1659     0.000000  ...              0
6511     0.666667  ...              0

[5 rows x 30 columns]

In [145]:
new_dfXtest = X_test[best_col]
new_dfXtest

REGION_ID_1  ...  JOB_ID_SA_REP
3317     0.333333  ...              0
5109     0.333333  ...              0
3274     0.333333  ...              0
9108     1.000000  ...              0
545      0.000000  ...              0
...           ...  ...            ...
8025     1.000000  ...              0
3185     0.333333  ...              0
7468     0.666667  ...              1
4924     0.333333  ...              1
4048     0.333333  ...              0

[2650 rows x 30 columns]

In [146]:
new_dfXtrain.shape,new_dfXtest.shape

((7950, 30), (2650, 30))

In [147]:
linmodel.fit(new_dfXtrain,y_train)

LinearRegression()

In [148]:
y_pred = linmodel.predict(new_dfXtest)

In [149]:
df_coeff = pd.DataFrame({'columns':new_dfXtrain.columns,'coeff':linmodel.coef_})
df_coeff

columns         coeff
0                                         REGION_ID_1  2.283889e+16
1                     DEPARTMENT_NAME_Human Resources -2.705317e+15
2                            DEPARTMENT_NAME_Shipping  2.729588e+15
3                                         CITY_London -2.330040e+15
4                                         CITY_Oxford -6.497340e+15
5                            CITY_South San Francisco -1.368566e+15
6                                        CITY_Toronto -1.459541e+15
7                                       COUNTRY_ID_CA -1.417078e+15
8                                       COUNTRY_ID_DE -1.966927e+15
9                                       COUNTRY_ID_UK -6.330746e+14
10                                      COUNTRY_ID_US -8.144767e+15
11                             STATE_PROVINCE_Bavaria -2.159221e+15
12                          STATE_PROVINCE_California -1.227961e+14
13                             STATE_PROVINCE_Ontario -2.410175e+15
14                              STATE_PROVINCE_Oxford  1.652634e+15
15                               STATE_PROVINCE_Texas -2.466518e+14
16                          STATE_PROVINCE_Washington -2.466518e+14
17                     STREET_ADDRESS_147 Spadina Ave -1.296440e+15
18                 STREET_ADDRESS_2011 Interiors Blvd -1.484877e+15
19                      STREET_ADDRESS_8204 Arthur St -2.600191e+15
20  STREET_ADDRESS_Magdalen Centre, The Oxford Sci...  3.468020e+15
21               STREET_ADDRESS_Schwanthalerstr. 7031 -2.159221e+15
22                                   REGION_NAME_Asia -7.612965e+15
23                                 REGION_NAME_Europe  7.612965e+15
24                 REGION_NAME_Middle East and Africa -1.522593e+16
25                                      JOB_ID_MK_MAN -1.808184e+15
26                                      JOB_ID_MK_REP -1.808184e+15
27                                      JOB_ID_PR_REP -2.106049e+15
28                                      JOB_ID_SA_MAN -6.381658e+15
29                                      JOB_ID_SA_REP -6.381658e+15

In [150]:
residuals = pd.DataFrame({'pred':y_pred,'actul':y_test})
residuals.head()

pred    actul
3317   3503.250   7900.0
5109  12202.875  10500.0
3274   3503.250   5800.0
9108   3499.875   2600.0
545    3503.875   2400.0

In [151]:
from sklearn.metrics import r2_score

In [152]:
r2_score(y_pred,y_test)

0.13259645936293418