In [1]:
import numpy as np

In [16]:
p1=np.array([1.2,23.5,45,2])
p2=np.array([5,29.1,42.5,1.2])

In [17]:
p = p1-p2

In [18]:
abs(p)

array([3.8, 5.6, 2.5, 0.8])

In [19]:
np.abs(p).sum()

12.700000000000003

In [20]:
np.abs(p1-p2).sum()

12.700000000000003

# Eucledian distance

In [22]:
p1=np.array([10,5])
p2=np.array([1,20])

In [23]:
p = np.sqrt((p1-p2)**2)
p

array([ 9., 15.])

In [24]:
p1-p2

array([  9, -15])

In [25]:
(p1-p2)**2

array([ 81, 225])

In [29]:
((p1-p2)**2).sum()

306

In [27]:
np.sqrt(((p1-p2)**2).sum())

17.4928556845359

In [30]:
p1=np.array([2,5])
p2=np.array([8,4])

In [31]:
np.abs(p1-p2).sum()

7

In [32]:
np.sqrt(((p1-p2)**2).sum())

6.082762530298219

In [33]:
p1=np.array([1,4,10])
p2=np.array([5,2,7])

In [34]:
np.sqrt(((p1-p2)**2).sum())

5.385164807134504

In [35]:
np.abs(p1-p2).sum()

9

In [36]:
p1=np.array([1.2,23.5,45,2])
p2=np.array([5,29.1,42.5,1.2])

In [37]:
np.abs(p1-p2).sum()

12.700000000000003

In [38]:
np.sqrt(((p1-p2)**2).sum())

7.258787777583804

In [41]:
(((p1-p2)**2).sum())**(1/2)

7.258787777583804

#Minkowiski

In [42]:
(((p1-p2)**3).sum())**(1/3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in double_scalars
  """Entry point for launching an IPython kernel.


nan

In [43]:
(p1-p2)**3

array([ -54.872, -175.616,   15.625,    0.512])

In [52]:
k=5
np.abs(((p1-p2)**k).sum())**(1/k)

5.734584385424231

# Penguin Example

In [57]:
p1=np.array([191,4600])
p2=np.array([218,4400])
p3=np.array([217,5000])

In [54]:
k=2
np.abs(((p1-p2)**k).sum())**(1/k)

201.8142710513803

In [55]:
np.abs(p1-p2).sum()

227

In [58]:
np.abs(p1-p3).sum()

426

In [59]:
np.abs(p2-p3).sum()

601

In [60]:
p1=np.array([191,460])
p2=np.array([218,440])
p3=np.array([217,500])

In [61]:
np.abs(p1-p2).sum()

47

In [62]:
np.abs(p1-p3).sum()

66

In [63]:
np.abs(p2-p3).sum()

61

In [64]:
p1=np.array([0.322,0.527])
p2=np.array([0.779,0.472])
p3=np.array([0.762,0.639])

In [65]:
np.abs(p1-p2).sum()

0.512

In [66]:
np.abs(p1-p3).sum()

0.552

In [67]:
np.abs(p2-p3).sum()

0.18400000000000005